name: phpunit

on:
  pull_request: {}
  release: {}
  push:
    branches: [ master ]

jobs:
  tests:
    name: unit tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [7.3, 7.4, 8.0, 8.1, 8.2 ]

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: phpunit tests ${{ matrix.php-versions }}
        uses: php-actions/phpunit@v3
        with:
          configuration: test/phpunit.xml
          php_extensions: pcov
          php_version: ${{ matrix.php-versions }}
          #vendored_phpunit_path: vendor/bin/phpunit
          version: 9.6

      - name: coverage monitor
        uses: slavcodev/coverage-monitor-action@1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: test/clover.xml
          comment_footer: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test/clover.xml
          name: github-ci
          verbose: true